
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/header";
import Samplenavbar from "./components/samplenavbar";
import BootstrapLoader from "./components/BootstrapLoader"; 
import { AuthProvider } from '@/lib/auth-context'

import "bootstrap/dist/css/bootstrap.min.css"; 
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "B2BNet - Business Networking Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <AuthProvider>
        <BootstrapLoader /> 
        <Header className="sticky-top" />
        <Samplenavbar />
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}

