
// import { Geist, Geist_Mono } from "next/font/google";
// import Header from "./components/header";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "bootstrap/dist/js/bootstrap.bundle.min.js"; // Bootstrap JS (with Popper.js)

// import Samplenavbar from "./components/samplenavbar";

// import "./globals.css";
// // import "./auth.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "B2BNet - Business Networking Platform",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/images/logo.png", // Path to your favicon in /public
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
      
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <Header className="sticky-top"/>
//         <Samplenavbar/>
//         {children}
//       </body>
//     </html>
//   );
// }
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/header";
import Samplenavbar from "./components/samplenavbar";
import BootstrapLoader from "./components/BootstrapLoader"; // ✅ Load Bootstrap JS in a Client Component

import "bootstrap/dist/css/bootstrap.min.css"; // ✅ Keep Bootstrap CSS at the top
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ `metadata` stays in this server component (no `use client` needed)
export const metadata = {
  title: "B2BNet - Business Networking Platform",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapLoader /> {/* ✅ Load Bootstrap JS in the browser */}
        <Header className="sticky-top" />
        <Samplenavbar />
        {children}
      </body>
    </html>
  );
}

